oxid:
    resource: "@OxidBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: @AppBundle/Controller/
#    type:     annotation

app:
    resource: @AppBundle/Resources/config/routing.yml

# Meta route that is called by OngrRouterBundle.
ongr_product:
    pattern:  /productDocument/{document}/ # This pattern is ignored and required for compatibility with Symfony.
    defaults: { _controller: AppBundle:Product:document }

# Actual route for accessing by document id (not SEO).
ongr_product_show:
    pattern:  /product/{id}
    defaults: { _controller: AppBundle:Product:show }
    requirements:
        page:  \d+

# Meta route that is called by OngrRouterBundle.
ongr_content:
    pattern:  /contentDocument/{document}/
    defaults: { _controller: AppBundle:Content:document }

# Actual route for accessing by document id (not SEO).
ongr_content_show:
    pattern:  /content/{id}
    defaults: { _controller: AppBundle:Content:show }
    requirements:
        page:  \d+
