ongr_es_home:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

ongr_filter_page:
    pattern: /list
    methods:  [GET]
    defaults:
        _controller: AppBundle:List:index
# to use original controller
#        _controller: ONGRFilterManagerBundle:Manager:manager
#        managerName: "default"
#        template: "AppBundle:List:results.html.twig"